name: Build GKI

on:
  workflow_dispatch:
   inputs:
   
    Build_Type:
     description: 'Build Type'
     required: true
     default: 'Single Image'
     type: choice
     options:
     - 'Single Image'
     - 'Multi'

    KernelSU:
     description: 'KernelSU'
     required: true
     default: 'Non-KSU'
     type: choice
     options:
     - 'OG KernelSU'
     - 'KernelSU-Next'
     - 'MKSU'
     - 'Non-KSU'


    SUSFS4KSU:
     description: 'SUSFS4KSU (KSU needed!)'
     required: false
     default: false
     type: boolean
     
    RELEASEGH:
     description: 'Release to GitHub'
     required: false
     default: false
     type: boolean

jobs:
  build:
    name: Build GKI Kernel
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
       swap-size-gb: 10

    - name: Install dependencies
      run: |
       sudo apt update -y
       sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
       sudo aptitude install libssl-dev -y

    - name: Build
      run: |
       chmod a+x *.sh

       if [[ "${{ inputs.SUSFS4KSU }}" == "true" ]]; then
            export USE_KSU_SUSFS="yes"
       fi
       

       if [[ "${{ inputs.KernelSU }}" == "OG KernelSU" ]]; then
            export USE_KSU="yes"
       elif [[ "${{ inputs.KernelSU }}" == "KernelSU-Next" ]]; then
            export USE_KSU_NEXT="yes"
       elif [[ "${{ inputs.KernelSU }}" == "MKSU" ]]; then
            export USE_KSU_MKSU="yes"
       fi
       
       if [[ "${{ inputs.RELEASEGH }}" == "true" ]]; then
            export RELEASE_INTO_GH="yes"
       fi

       export chat_id="${{ secrets.CHAT_ID }}"
       export token="${{ secrets.TOKEN }}"
       export gh_token="${{ secrets.GH_TOKEN }}"
       export build_type="${{ inputs.Build_Type }}"

       ./build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: kernel.zip
       path: /home/runner/work/gki-builder/gki-builder/kernel.zip
