name: Release Build

on:
  workflow_dispatch:

jobs:
  non-ksu:
    name: Build Non-KSU
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KernelSU: None
      SUSFS4KSU: "false"
      Clang: Default
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "false"
      KSU_MANUAL_HOOK: "false"

  ksuxsusfs:
    name: Build KSUxSuSFS
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KernelSU: Official
      SUSFS4KSU: "true"
      Clang: Default
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "false"
      KSU_MANUAL_HOOK: "false"

  ksunxsusfs:
    name: Build KSU-Next with SuSFS
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KernelSU: Next
      SUSFS4KSU: "true"
      Clang: Default
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "false"
      KSU_MANUAL_HOOK: "true"
      LAST_BUILD: "true"

  release:
    name: Create Unified Release
    needs: [non-ksu, ksuxsusfs, ksunxsusfs]  # Waits for all build to be complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files

      - name: List Downloaded Files
        run: ls -R release_files

      - name: Extract variables from info.txt
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" # for debugging
            echo "$key=$value" >> $GITHUB_ENV
          done < release_files/info-${{ github.run_number }}/info.txt
          rm -f release_files/info-${{ github.run_number }}/info.txt

      - name: Upload All Builds to GKI Release Repo
        uses: softprops/action-gh-release@v2
        with:
          repository: "${{ env.REL_REPO }}"
          name: "${{ env.RELEASE_NAME }}"
          tag_name: "${{ github.run_id }}"
          files: release_files/**/*
          body: |
            -> Linux ${{ env.KVER }}
            -> KSU Next ${{ env.KSU_NEXT_VER }}
            -> KSU Official ${{ env.KSU_OFC_VER }}
            -> SUSFS ඞ ${{ env.SUSFS_VER }}
            -> KSU Next Manual Hooks
            
            [GKI Builder](${{ env.BUILDER_REPO }}):
            -> Last Commit: [here](${{ env.BUILDER_LAST_COMMIT }})
            -> Branch: ${{ env.BUILDER_BRANCH }}
            
            [Kernel Source](${{ env.KERNEL_REPO }}): 
            -> Last Commit: [here](${{ env.KERNEL_LAST_COMMIT }})     
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
