name: Build GKI - Release
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch:

env:
  STATUS: "STABLE"
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BUILD_KERNEL: "true"
  MAN_DISABLE: "true"

jobs:
  non-ksu:
    name: Build Non-KSU
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      KernelSU: "None"
      SUSFS4KSU: "false"
      Clang: "Default"
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "true"
      KSU_MANUAL_HOOK: "false"

  ksuxsusfs:
    name: Build KSUxSuSFS
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      KernelSU: "Official KernelSU"
      SUSFS4KSU: "true"
      Clang: "Default"
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "true"
      KSU_MANUAL_HOOK: "false"

  ksunxsusfs:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      KernelSU: "KernelSU-Next"
      SUSFS4KSU: "true"
      Clang: "Default"
      BUILD_BOOTIMG: "true"
      UPLOAD2GH: "true"
      BUILD_LKMS: "true"
      KSU_MANUAL_HOOK: "false"
