name: Build GKI - Release

on:
  workflow_dispatch:

env:
  STATUS: "STABLE"
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MAN_DISABLE: "true"

jobs:
  non-ksu:
    name: Build Non-KSU variant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build
        run: |
          chmod a+x *.sh
          ./build.sh

  ksu:
    name: Build KSU variant
    needs: non-ksu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU=yes
          ./build.sh

  ksun:
    name: Build KSU-Next variant
    needs: ksu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU_NEXT=yes
          ./build.sh

  ksuxsusfs:
    name: Build KSUxSuSFS variant
    needs: ksun
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU=yes
          export USE_KSU_SUSFS=yes
          ./build.sh

  ksunxsusfs:
    name: Build KSUNxSuSFS variant
    needs: ksuxsusfs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU_NEXT=yes
          export USE_KSU_SUSFS=yes
          ./build.sh
