name: Build GKI - Release

on:
  workflow_dispatch:

env:
  STATUS: "STABLE"
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BUILD_KERNEL: "true"
  MAN_DISABLE: "true"

jobs:
  non-ksu:
    name: Build Non-KSU
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools ccache -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: kernel-${{ github.ref_name }}
          max-size: 4G
          restore-keys: |
            kernel-${{ github.ref_name }}-
            kernel-

      - name: Build
        run: |
          chmod a+x *.sh
          export PATH="/usr/lib/ccache:$PATH"
          ./build.sh

  ksuxsusfs:
    name: Build KSUxSuSFS
    needs: non-ksu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools ccache -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: kernel-${{ github.ref_name }}
          max-size: 4G
          restore-keys: |
            kernel-${{ github.ref_name }}-
            kernel-

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU=true
          export USE_KSU_SUSFS=true
          export PATH="/usr/lib/ccache:$PATH"
          ./build.sh

  ksunxsusfs:
    name: Build KSUNxSuSFS
    needs: ksuxsusfs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools ccache -y
          sudo aptitude install libssl-dev -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: kernel-${{ github.ref_name }}
          max-size: 4G
          restore-keys: |
            kernel-${{ github.ref_name }}-
            kernel-

      - name: Build
        run: |
          chmod a+x *.sh
          export USE_KSU_NEXT=true
          export USE_KSU_SUSFS=true
          export PATH="/usr/lib/ccache:$PATH"
          ./build.sh
