name: Build GKI - TEST

on:
  workflow_call:      # Allows calling from another workflow
   inputs:

    KernelSU:
      required: true
      type: string

    SUSFS4KSU:
      required: false
      type: string

    Clang:
      required: true
      type: string

    BUILD_BOOTIMG:
      required: false
      type: string

    UPLOAD2GH:
      required: false
      type: string

    BUILD_LKMS:
      required: false
      type: string

    KSU_MANUAL_HOOK:
      required: false
      type: string
      
  workflow_dispatch: # Allows triggering workflow manually
   inputs:

    KernelSU:
      description: 'KernelSU'
      required: false
      default: 'None'
      type: choice
      options:
      - 'None'
      - 'Official KernelSU'
      - 'KernelSU-Next'
      - 'Rissu KernelSU Fork'

    SUSFS4KSU:
      description: 'SUSFS4KSU (KSU needed!)'
      default: false
      type: boolean

    Clang:
      description: 'Select Compiler'
      required: false
      default: 'Default'
      type: choice
      options:
      - 'Default'
      - 'AOSP Clang'
      - 'Custom Clang'

    BUILD_BOOTIMG:
      description: 'Build Boot Image'
      default: false
      type: boolean

    UPLOAD2GH:
      description: 'Upload to GitHub Release'
      default: false
      type: boolean

    BUILD_LKMS:
      description: 'Build Loadable Kernel Module (.ko)'
      default: true
      type: boolean

    KSU_MANUAL_HOOK:
      description: 'KSU Manual Hook'
      default: false
      type: boolean

jobs:
  build:
    name: Build GKI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
       export MAN_DISABLE=true
       sudo apt update -y
       sudo apt install bc cpio flex bison aptitude gh git python-is-python3 tar perl wget curl lz4 zstd libarchive-tools ccache -y
       sudo aptitude install libssl-dev -y

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: kernel cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: |
          ccache-${{ github.ref_name }}-
          ccache-

    - name: clang cache
      uses: actions/cache@v3
      with:
        path: android-kernel/clang
        key: clang-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: |
          clang-${{ github.ref_name }}-
          clang-

    - name: Build
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        STATUS: "BETA"
        BUILD_KERNEL: "true"
      run: |
       chmod a+x *.sh

       if [[ "${{ inputs.KernelSU }}" != "None" ]]; then
            export USE_KSU="true"
       fi

       # KSU Manual hook
       if [[ "${{ inputs.KSU_MANUAL_HOOK }}" == "true" ]]; then
            sed -i 's/KSU_USE_MANUAL_HOOK=.*/KSU_USE_MANUAL_HOOK=true/g' config.sh
       else
            sed -i 's/KSU_USE_MANUAL_HOOK=.*/KSU_USE_MANUAL_HOOK=false/g' config.sh
       fi

       if [[ "${{ inputs.SUSFS4KSU }}" == "true" ]]; then
            export USE_KSU_SUSFS="true"
       fi

       if [[ "${{ inputs.KernelSU }}" == "Official KernelSU" ]]; then
            export USE_KSU_OFC="true"
       elif [[ "${{ inputs.KernelSU }}" == "KernelSU-Next" ]]; then
            export USE_KSU_NEXT="true"
       elif [[ "${{ inputs.KernelSU }}" == "Rissu KernelSU Fork" ]]; then
            export USE_KSU_RKSU="true"
       fi

       if [[ "${{ inputs.BUILD_LKMS }}" == "true" ]]; then
            export BUILD_LKMS="true"
       fi

       if [[ "${{ inputs.Clang }}" == "AOSP Clang" ]]; then
            sed -i 's/USE_CUSTOM_CLANG=.*/USE_CUSTOM_CLANG=false/g' config.sh
            sed -i 's/USE_AOSP_CLANG=.*/USE_AOSP_CLANG=true/g' config.sh
       elif [[ "${{ inputs.Clang }}" == "Custom Clang" ]]; then
            sed -i 's/USE_CUSTOM_CLANG=.*/USE_CUSTOM_CLANG=true/g' config.sh
            sed -i 's/USE_AOSP_CLANG=.*/USE_AOSP_CLANG=false/g' config.sh
       elif [[ "${{ inputs.Clang }}" == "Default" ]]; then
            : # follow config.sh
       fi

       if [[ "${{ inputs.BUILD_BOOTIMG }}" == "true" ]]; then
            export BUILD_BOOTIMG="true"
       fi

       if [[ "${{ inputs.UPLOAD2GH }}" == "true" ]]; then
            export UPLOAD2GH="true"
       fi

       export PATH="/usr/lib/ccache:$PATH"
       ./build.sh

    - name: Upload kernel zip
      uses: actions/upload-artifact@v4
      if: inputs.UPLOAD2GH == false
      with:
        name: kernel-${{ github.run_number }}
        path: "./*.zip"

    - name: Upload boot image (gzip)
      uses: actions/upload-artifact@v4
      if: inputs.BUILD_BOOTIMG == true && inputs.UPLOAD2GH == false
      with:
        name: boot-gz-${{ github.run_number }}
        path: "./*-gz.img"

    - name: Upload boot image (lz4)
      uses: actions/upload-artifact@v4
      if: inputs.BUILD_BOOTIMG == true && inputs.UPLOAD2GH == false
      with:
        name: boot-lz4-${{ github.run_number }}
        path: "./*-lz4.img"

    - name: Upload boot image (raw)
      uses: actions/upload-artifact@v4
      if: inputs.BUILD_BOOTIMG == true && inputs.UPLOAD2GH == false
      with:
        name: boot-raw-${{ github.run_number }}
        path: "./*-raw.img"
